### ISSUE TITLE
. 

### ISSUE THREAD

**Issue by jamalnggau1** [caraka15/plume-bot#1]
bang buat contoh .env nya

**Comment by jamalnggau1** [comment]
create .env file

**Comment by caraka15** [comment]
oke bang, masih coba2, kalo checkin udah oke, kalo task yang lain dijalanin pake bot tanpa buka website nya bakal nambah ga point nya,
nanti gw bakal buatin readme nya

**Comment by caraka15** [comment]
> bang buat contoh .env nya

cek readme bang, sudah ku buat

**Comment by jamalnggau1** [comment]
lu punya tele ngg bang? atau grub gitu?
